### ISSUE TITLE
请问您复现YOLOv7的时候，图像预处理都使用了什么？我在DUO数据集上测试的YOLOv7和您论文中报告的有些出入。期待回答

### ISSUE THREAD

**Issue by wenxinss** [Ixiaohuihuihui/GCC-Net#12]

**Comment by wenxinss** [comment]
我在复现YOLOv7时除了马赛克增强，其他的数据增强我都使用了。

**Comment by Ixiaohuihuihui** [comment]
就是使用的yolov7源代码呀～～～可以看我上传的config

**Comment by shf311709001219** [comment]
> 我在复现YOLOv7时除了马赛克增强，其他的数据增强我都使用了。

你复现的时候指标跟论文给出的差的多吗，我差的还是比较多的

**Comment by shf311709001219** [comment]
> 我在复现YOLOv7时除了马赛克增强，其他的数据增强我都使用了。

你复现的时候指标跟论文给出的差的多吗，我差的还是比较多的


> 我在复现YOLOv7时除了马赛克增强，其他的数据增强我都使用了。


你复现的时候指标跟论文给出的差的多吗，我差的还是比较多的

**Comment by Ixiaohuihuihui** [comment]
那我不知道了，我在两个服务器上都跑过yolov7,,我用的是mmyolo这个仓库的代码噢

**Comment by wenxinss** [comment]
> > 我在复现YOLOv7时除了马赛克增强，其他的数据增强我都使用了。
> 
> 你复现的时候指标跟论文给出的差的多吗，我差的还是比较多的

我用的是yolov7-main的代码，在加载数据集的代码中直接把马赛克增强的那个true改为false，其他的都没动。
