### ISSUE TITLE
关于wpbb数据集配置问题

### ISSUE THREAD

**Issue by shf311709001219** [Ixiaohuihuihui/GCC-Net#15]
train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        pipeline=train_pipeline),
请问根据你给的链接下载的WPBB数据集，下载后怎么配置这部分呀

**Comment by Ixiaohuihuihui** [comment]
看下WPBB的数据集说明
