### ISSUE TITLE
关于创新模块代码在哪个文件夹

### ISSUE THREAD

**Issue by 289282737** [Ixiaohuihuihui/GCC-Net#17]
您好，我是一个新手，我想知道您的代码中跨域特征交互和门控特征融合模块在哪个文件夹中呢，我没有找到，我想看看 谢谢您

**Comment by Ixiaohuihuihui** [comment]
如果您是新手，请研究一下mmdetection框架的代码

**Comment by 289282737** [comment]
谢谢您的建议，我现在环境装到这里，运行这个python tools/train.py configs/autoassign/autoassign_r50_fpn_8x2_3x_gcc_wpbb.py --gpus 2
出现这个错误怎么办呢 KeyError: 'AutoAssign_fusion is not in the models registry'

**Comment by Ixiaohuihuihui** [comment]
你应该是没安装好。
