### ISSUE TITLE
关于GCC模型训练的显存占用问题

### ISSUE THREAD

**Issue by zhaoliming386962** [Ixiaohuihuihui/GCC-Net#18]
作者您好，非常感谢您做了如此棒的工作，我在尝试使用您的代码进行训练实现的时候，遇到了显存占用上的一些疑问，我使用单卡RTX3090,24G显存，batch_size只能设置成4，在此种情况下，占用了22G的显存。这对于我是有点反直觉的尽管GCC模型的确很庞大，我想确认这是否是正常的。
我在您的代码中看到您使用了8块GPU，每块GPU的Batch_size是2，想问问您关于显存的配置，您使用什么显卡进行训练的，每块GPU的显存是多少，作为借鉴。
![image](https://github.com/user-attachments/assets/467ad8c2-8c8c-4a4b-8e0b-f08d553fa608)

**Comment by Ixiaohuihuihui** [comment]
你的没错，大概就是占了这么多显存。我用4090，2张卡，batch size是2.

**Comment by zhaoliming386962** [comment]
谢谢您的回答，这解决了我的困惑

**Comment by BAI-WQ** [comment]
> 作者您好，非常感谢您做了如此棒的工作，我在尝试使用您的代码进行训练实现的时候，遇到了显存占用上的一些疑问，我使用单卡RTX3090,24G显存，batch_size只能设置成4，在此种情况下，占用了22G的显存。这对于我是有点反直觉的尽管GCC模型的确很庞大，我想确认这是否是正常的。 我在您的代码中看到您使用了8块GPU，每块GPU的Batch_size是2，想问问您关于显存的配置，您使用什么显卡进行训练的，每块GPU的显存是多少，作为借鉴。 ![image](https://private-user-images.githubusercontent.com/167155486/387078561-467ad8c2-8c8c-4a4b-8e0b-f08d553fa608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzczNTAsIm5iZiI6MTczMjY3NzA1MCwicGF0aCI6Ii8xNjcxNTU0ODYvMzg3MDc4NTYxLTQ2N2FkOGMyLThjOGMtNGE0Yi04ZTBiLWYwOGQ1NTNmYTYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMzEwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDM5NTA5ZGRiMzk4ZjJkZjk1NzU1NTViMzExMTY2YzBiMDVkYjE4MWVmYTZiZjJjMDcwZTE2YzI3ZTIwZTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R5BqLBY6iIImNUFvzKDdJfyBOFeGQewSZHfChPeTgFM)

你好我也想要单卡3090训练，请问一下您是怎么调整代码的啊，我按照作者的要求进行环境配置现在有一些问题可以请教您一下吗

**Comment by zhaoliming386962** [comment]
关于如何配置环境和运行代码，作者的文档中已经写的很详细了，我按照作者的文档进行环境配置和代码运行一切都很顺利。
而且作者的代码习惯很好，代码结构很清晰，必要的地方加上了注释，如果有什么具体的问题在文档中找不到答案的，我会把我知道的告诉你

**Comment by BAI-WQ** [comment]
> 关于如何配置环境和运行代码，作者的文档中已经写的很详细了，我按照作者的文档进行环境配置和代码运行一切都很顺利。 而且作者的代码习惯很好，代码结构很清晰，必要的地方加上了注释，如果有什么具体的问题在文档中找不到答案的，我会把我知道的告诉你

感谢感谢，我是租用的3090的服务器，想在DUO数据集上运行代码，下载的mmdet=2.24.1  mmcv-full=1.5.0,运行单卡训练的代码CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/autoassign/autoassign_r50_fpn_8x2_3x_gcc_duo.py，但是现在报错KeyError: 'AutoAssign_fusion is not in the models registry'没有找到解决方案，请问您知道这个是什么原因吗

**Comment by zhaoliming386962** [comment]
RTX3090
conda env name 	= mmdetection2.x
python			=3.7.0
cuda			=11.1.0
cudnn			=8.8.0 for cuda111
torch			=1.8.0 for cuda111 cp37
torchvision		=0.9.0 for cuda111 cp37
mmcv			=1.6.0
mmdet			=2.24.1
这是我的环境配置，看起来你的配置是没有问题的，你的错误显示AutoAssign_fusion没有被注册，这是反常的，你是否更改过代码，我在使用过程是并未遇到此类问题，一切都很正常，你可以尝试重新clone作者的仓库进行尝试，我很难给出你其它建议

**Comment by BAI-WQ** [comment]
> RTX3090 conda env name = mmdetection2.x python =3.7.0 cuda =11.1.0 cudnn =8.8.0 for cuda111 torch =1.8.0 for cuda111 cp37 torchvision =0.9.0 for cuda111 cp37 mmcv =1.6.0 mmdet =2.24.1 这是我的环境配置，看起来你的配置是没有问题的，你的错误显示AutoAssign_fusion没有被注册，这是反常的，你是否更改过代码，我在使用过程是并未遇到此类问题，一切都很正常，你可以尝试重新clone作者的仓库进行尝试，我很难给出你其它建议

好的好的，感谢您的回复，我再看看要不重新clone
