### ISSUE TITLE
AutoAssign_fusion is not in the models registry

### ISSUE THREAD

**Issue by BAI-WQ** [Ixiaohuihuihui/GCC-Net#19]
作者您好！我对您的项目非常感兴趣，但是在复现过程中有个问题想请教一下。
请问一下我是用的3090单卡训练，想在DUO数据集上运行代码，下载的mmdet=2.24.1 mmcv-full=1.5.0,torch  =1.8.0+cu111  
python    =3.8.20            运行单卡训练的代码CUDA_VISIBLE_DEVICES=0 python tools/train.pyconfigs/autoassign/autoassign_r50_fpn_8x2_3x_gcc_duo.py，但是现在报错KeyError: 'AutoAssign_fusion is not in the models registry'没有找到解决方案，请问这个是什么原因啊

**Comment by BAI-WQ** [comment]
/
![0ee777c3c6a65c2f00bd4e0d280a26d](https://github.com/user-attachments/assets/e2ed677a-26a9-46fd-a945-ca0ce068d637)
![757a73e162407cca82b595a04ab86cc](https://github.com/user-attachments/assets/550fbf8b-0c56-4aa9-a6f1-83a04ae47fe7)

**Comment by BAI-WQ** [comment]
解决了，我重新配置了一下感谢感谢

**Comment by Ixiaohuihuihui** [comment]
好的

**Comment by Mariiiiooooo** [comment]
> 解决了，我重新配置了一下感谢感谢

请问是怎么解决的呀，同样报错了

**Comment by BAI-WQ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jhhhhkj** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。 我将在假期结束后，尽快给您回复。

怎么解决的呢？

**Comment by BAI-WQ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
