### ISSUE TITLE
GatedFeatureFusion模块使用

### ISSUE THREAD

**Issue by cluking** [Ixiaohuihuihui/GCC-Net#22]
请问在SwinFusionTransformer中为何要注释掉GatedFeatureFusion的使用，而是直接使用相加的操作。是在别的代码中有重新用到GFF模块融合吗？

**Comment by Ixiaohuihuihui** [comment]
对，我传的这个版本注释掉了，其实不需要GFF已经能达到很好的性能了。你也可以选择取消注释。

**Comment by cluking** [comment]
好的，谢谢，很棒的工作
