### ISSUE TITLE
In figure 2 of the paper, what does this stand for PM?

### ISSUE THREAD

**Issue by xlnn** [Ixiaohuihuihui/GCC-Net#3]
Thank you for your excellent work, I have a question, in figure 2 of the paper, what does this stand for PM? It doesn't seem to be mentioned in your paper, thank you!

**Comment by Ixiaohuihuihui** [comment]
Hi, thanks for your comments. The 'PM' denotes the patch merging in Swin transformer, which is used to produce a hierarchical representation.

**Comment by xlnn** [comment]
> Hi, thanks for your comments. The 'PM' denotes the patch merging in Swin transformer, which is used to produce a hierarchical representation.

I appreciate your answer, thank you!
