### ISSUE TITLE
I have found a problem why I am using DUO data with IOU=0.50 with AP equal to 0.

### ISSUE THREAD

**Issue by xlnn** [Ixiaohuihuihui/GCC-Net#5]
Thanks for your excellent work, I have found a problem why I am using DUO data with IOU=0.50 with AP equal to 0. As shown below.Thank you！
`Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000`
 `Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000`

**Comment by xlnn** [comment]
Oh! I know: in mmdet/datasets/utdac.py, i set iou_thrs = [0.5] . It should is None. That should be the problem.Thank you!

**Comment by Ixiaohuihuihui** [comment]
OK!^_^
