### ISSUE TITLE
我使用DUO数据集，其它全部默认，最后的结果(AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.852

### ISSUE THREAD

**Issue by xlnn** [Ixiaohuihuihui/GCC-Net#7]
作者您好，我使用DUO数据集，其它全部默认，训练了多次为什么最终的结果全是：(AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.852，没有达到0.878，您知道什么情况吗？感谢您出色的工作！！

**Comment by Ixiaohuihuihui** [comment]
你用几张显卡？

**Comment by Ixiaohuihuihui** [comment]
学习率这些都要查

**Comment by Ixiaohuihuihui** [comment]
学习率这些都要重新调整

**Comment by xlnn** [comment]
> 你用几张显卡？

我是用的是两张显卡32G的

**Comment by xlnn** [comment]
> 学习率这些都要重新调整

我能冒昧的问您一下，学习率应该调整多少吗？谢谢您！

**Comment by Ixiaohuihuihui** [comment]
你把测试log发我邮箱，我看下。

**Comment by xlnn** [comment]
> 你把测试log发我邮箱，我看下。

好的，您稍等一下，谢谢！

**Comment by xlnn** [comment]
> 你把测试log发我邮箱，我看下。

作者您好，已发送给您训练日志，epoch_36.pt以及测试结果，请查收，谢谢！
