### ISSUE TITLE
The number of images in the test and validation sets of the Brackish dataset is inconsistent with the one provided in the paper.

### ISSUE THREAD

**Issue by Calendula597** [Ixiaohuihuihui/GCC-Net#9]
The number of images in the test and validation sets in COCO format is 1239 and 1238, they do not match 1468 and 1467 in the paper. Could you please provide the COCO format annotation file of Brackish dataset that were used in the project?

**Comment by Ixiaohuihuihui** [comment]
It doesn't matter. The dataset you used are 1239 and 1238. Just use it.
<img width="463" alt="image" src="https://github.com/Ixiaohuihuihui/GCC-Net/assets/26215859/136b5b5c-fd7f-4928-9031-b768481d0208">
<img width="469" alt="image" src="https://github.com/Ixiaohuihuihui/GCC-Net/assets/26215859/64e5dc4a-32f8-4faa-841e-d771fabaff71">
